/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.udec.simuladorpeaje.vista;

import com.udec.simuladorpeaje.toFile.ToExcel;
import com.udec.simuladorpeaje.validaciones.Ayuda;

import javax.swing.*;
import java.awt.event.KeyEvent;
import java.util.ArrayList;

/**
 *
 * @author PedroD
 */
public class JPMitchelMoore extends javax.swing.JPanel {

    /**
     *
     */
    public static ArrayList<Float> resultados = new ArrayList<>();
    private ToExcel a = new ToExcel();

    /**
     * Creates new form JPMitchelMoore
     */
    public JPMitchelMoore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JPvariables = new javax.swing.JPanel();
        JTmodulo = new javax.swing.JTextField();
        JBlimpiar = new javax.swing.JButton();
        JBgenerar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTn = new javax.swing.JTextField();
        JPnumerosgenerados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        JLperiodo = new javax.swing.JLabel();
        JPpruebas = new javax.swing.JPanel();
        JBpromedios1 = new javax.swing.JButton();
        JBfrecuencias1 = new javax.swing.JButton();
        JBdistancias1 = new javax.swing.JButton();
        JBkolgomorov1 = new javax.swing.JButton();
        JBpoker1 = new javax.swing.JButton();
        JBcorridas3 = new javax.swing.JButton();
        JBcorridas4 = new javax.swing.JButton();
        JBseries1 = new javax.swing.JButton();
        JLpromedio1 = new javax.swing.JLabel();
        JLfrecuencias1 = new javax.swing.JLabel();
        JLdistancias1 = new javax.swing.JLabel();
        JLkolgomorov1 = new javax.swing.JLabel();
        JLpoker1 = new javax.swing.JLabel();
        JLcorridas3 = new javax.swing.JLabel();
        JLcorridas4 = new javax.swing.JLabel();
        JLseries1 = new javax.swing.JLabel();
        JPencabezado = new javax.swing.JPanel();
        JLnombre = new javax.swing.JLabel();
        JBguardar = new javax.swing.JButton();

        JPvariables.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Variables"));

        JTmodulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTmoduloActionPerformed(evt);
            }
        });
        JTmodulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTmoduloKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTmoduloKeyTyped(evt);
            }
        });

        JBlimpiar.setText("Limpiar");
        JBlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBlimpiarActionPerformed(evt);
            }
        });

        JBgenerar.setText("Generar");
        JBgenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBgenerarActionPerformed(evt);
            }
        });

        jLabel3.setText("n");

        jLabel2.setText("Modulo (m)");

        JTn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTnKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTnKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout JPvariablesLayout = new javax.swing.GroupLayout(JPvariables);
        JPvariables.setLayout(JPvariablesLayout);
        JPvariablesLayout.setHorizontalGroup(
            JPvariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPvariablesLayout.createSequentialGroup()
                .addGroup(JPvariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPvariablesLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(JBlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(JBgenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPvariablesLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(JPvariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(JPvariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTmodulo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        JPvariablesLayout.setVerticalGroup(
            JPvariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPvariablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPvariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTmodulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPvariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(JPvariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBgenerar)
                    .addComponent(JBlimpiar))
                .addGap(30, 30, 30))
        );

        JPnumerosgenerados.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Numeros Generados"));

        jScrollPane2.setViewportView(jList1);

        JLperiodo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLperiodo.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout JPnumerosgeneradosLayout = new javax.swing.GroupLayout(JPnumerosgenerados);
        JPnumerosgenerados.setLayout(JPnumerosgeneradosLayout);
        JPnumerosgeneradosLayout.setHorizontalGroup(
            JPnumerosgeneradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnumerosgeneradosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPnumerosgeneradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        JPnumerosgeneradosLayout.setVerticalGroup(
            JPnumerosgeneradosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnumerosgeneradosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPpruebas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Pruebas"));

        JBpromedios1.setText("Promedio");
        JBpromedios1.setEnabled(false);
        JBpromedios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBpromedios1ActionPerformed(evt);
            }
        });

        JBfrecuencias1.setText("Frecuencias");
        JBfrecuencias1.setEnabled(false);
        JBfrecuencias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBfrecuencias1ActionPerformed(evt);
            }
        });

        JBdistancias1.setText("Distancias");
        JBdistancias1.setEnabled(false);
        JBdistancias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBdistancias1ActionPerformed(evt);
            }
        });

        JBkolgomorov1.setText("Kolgomorov");
        JBkolgomorov1.setEnabled(false);
        JBkolgomorov1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBkolgomorov1ActionPerformed(evt);
            }
        });

        JBpoker1.setText("Poker");
        JBpoker1.setEnabled(false);
        JBpoker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBpoker1ActionPerformed(evt);
            }
        });

        JBcorridas3.setText("Corridas 1");
        JBcorridas3.setEnabled(false);
        JBcorridas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcorridas3ActionPerformed(evt);
            }
        });

        JBcorridas4.setText("Corridas 2");
        JBcorridas4.setEnabled(false);
        JBcorridas4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBcorridas4ActionPerformed(evt);
            }
        });

        JBseries1.setText("Series");
        JBseries1.setEnabled(false);
        JBseries1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBseries1ActionPerformed(evt);
            }
        });

        JLpromedio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLpromedio1.setText("-");

        JLfrecuencias1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLfrecuencias1.setText("-");

        JLdistancias1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLdistancias1.setText("-");

        JLkolgomorov1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLkolgomorov1.setText("-");

        JLpoker1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLpoker1.setText("-");

        JLcorridas3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLcorridas3.setText("-");

        JLcorridas4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLcorridas4.setText("-");

        JLseries1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLseries1.setText("-");

        javax.swing.GroupLayout JPpruebasLayout = new javax.swing.GroupLayout(JPpruebas);
        JPpruebas.setLayout(JPpruebasLayout);
        JPpruebasLayout.setHorizontalGroup(
            JPpruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPpruebasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPpruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBkolgomorov1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBdistancias1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBfrecuencias1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBpromedios1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPpruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLpromedio1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(JLfrecuencias1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLdistancias1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLkolgomorov1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JPpruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBseries1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBcorridas4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBcorridas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBpoker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JPpruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLpoker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLcorridas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLcorridas4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLseries1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPpruebasLayout.setVerticalGroup(
            JPpruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPpruebasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPpruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBpromedios1)
                    .addComponent(JBpoker1)
                    .addComponent(JLpoker1)
                    .addComponent(JLpromedio1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPpruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBfrecuencias1)
                    .addComponent(JBcorridas3)
                    .addComponent(JLfrecuencias1)
                    .addComponent(JLcorridas3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPpruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBdistancias1)
                    .addComponent(JBcorridas4)
                    .addComponent(JLdistancias1)
                    .addComponent(JLcorridas4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPpruebasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBkolgomorov1)
                    .addComponent(JBseries1)
                    .addComponent(JLkolgomorov1)
                    .addComponent(JLseries1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JLnombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JLnombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLnombre.setText("MitchelMoore");

        JBguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1408783509_shine_13.png"))); // NOI18N
        JBguardar.setText("Guardar");
        JBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBguardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPencabezadoLayout = new javax.swing.GroupLayout(JPencabezado);
        JPencabezado.setLayout(JPencabezadoLayout);
        JPencabezadoLayout.setHorizontalGroup(
            JPencabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPencabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(JBguardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPencabezadoLayout.setVerticalGroup(
            JPencabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPencabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPencabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLnombre)
                    .addComponent(JBguardar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JPencabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JPvariables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPpruebas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(JPnumerosgenerados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(JPencabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JPvariables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JPpruebas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JPnumerosgenerados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBguardarActionPerformed
        a.guardar(resultados);
    }//GEN-LAST:event_JBguardarActionPerformed

    private void JTmoduloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTmoduloKeyTyped
        soloNumero(evt);
    }//GEN-LAST:event_JTmoduloKeyTyped

    private void JTnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTnKeyTyped
        soloNumero(evt);
    }//GEN-LAST:event_JTnKeyTyped

    private void JBgenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBgenerarActionPerformed
        if (JTmodulo.getText().equals("0")) {
            JOptionPane.showMessageDialog(this, "El Modulo debe ser diferente de cero.");
        } else {
            if (!(JTmodulo.getText().equals("") || JTn.getText().equals(""))) {

                int n = Integer.parseInt(JTn.getText());
                int m = Integer.parseInt(JTmodulo.getText());
                resultados = new ArrayList<>();
                if (n > 54) {
                    if (!Ayuda.Impar(m)) {
                        resultados.addAll(com.udec.simuladorpeaje.vista.Run.cg.mitchellMoore(m, n));
                        Ayuda.listar(resultados, jList1, JLperiodo);
                    } else {
                        JOptionPane.showMessageDialog(this, "m debe ser par ");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "n>54");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Llene todos los campos", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
            Ayuda.habilitarb(resultados, JBpromedios1, JBfrecuencias1, JBdistancias1, JBkolgomorov1, JBpoker1, JBcorridas3, JBcorridas4, JBseries1);
        }
    }//GEN-LAST:event_JBgenerarActionPerformed

    private void JBlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBlimpiarActionPerformed
        JTmodulo.setText("");
        JTn.setText("");
        DefaultListModel lm = new DefaultListModel();
        jList1.setModel(lm);
        resultados = new ArrayList<>();
        JLperiodo.setText("");
        Ayuda.habilitarb(resultados, JBpromedios1, JBfrecuencias1, JBdistancias1, JBkolgomorov1, JBpoker1, JBcorridas3, JBcorridas4, JBseries1);
    }//GEN-LAST:event_JBlimpiarActionPerformed

    private void JTmoduloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTmoduloActionPerformed

    }//GEN-LAST:event_JTmoduloActionPerformed

    private void JTmoduloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTmoduloKeyPressed
        soloNumero(evt);
    }//GEN-LAST:event_JTmoduloKeyPressed

    private void JTnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTnKeyPressed
        soloNumero(evt);
    }//GEN-LAST:event_JTnKeyPressed

    private void JBpromedios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBpromedios1ActionPerformed
        JLpromedio1.setText(com.udec.simuladorpeaje.vista.Run.cp.pruebaPromedios(resultados));
    }//GEN-LAST:event_JBpromedios1ActionPerformed

    private void JBfrecuencias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBfrecuencias1ActionPerformed
        JLfrecuencias1.setText(com.udec.simuladorpeaje.vista.Run.cp.pruebaFrecuencia(resultados));
    }//GEN-LAST:event_JBfrecuencias1ActionPerformed

    private void JBdistancias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBdistancias1ActionPerformed
        JLdistancias1.setText(com.udec.simuladorpeaje.vista.Run.cp.pruebaDistancia(resultados));
    }//GEN-LAST:event_JBdistancias1ActionPerformed

    private void JBkolgomorov1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBkolgomorov1ActionPerformed
        JLkolgomorov1.setText(com.udec.simuladorpeaje.vista.Run.cp.pruebaKolgomorov(resultados));
    }//GEN-LAST:event_JBkolgomorov1ActionPerformed

    private void JBpoker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBpoker1ActionPerformed
        JLpoker1.setText(com.udec.simuladorpeaje.vista.Run.cp.pruebaPoker(resultados));
    }//GEN-LAST:event_JBpoker1ActionPerformed

    private void JBcorridas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcorridas3ActionPerformed
        JLcorridas3.setText(com.udec.simuladorpeaje.vista.Run.cp.pruebaCorridas1(resultados));
    }//GEN-LAST:event_JBcorridas3ActionPerformed

    private void JBcorridas4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBcorridas4ActionPerformed
        JLcorridas4.setText(com.udec.simuladorpeaje.vista.Run.cp.pruebaCorridas2(resultados));
    }//GEN-LAST:event_JBcorridas4ActionPerformed

    private void JBseries1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBseries1ActionPerformed
        JLseries1.setText(com.udec.simuladorpeaje.vista.Run.cp.pruebaSerie(resultados));
    }//GEN-LAST:event_JBseries1ActionPerformed
    private void soloNumero(java.awt.event.KeyEvent evt) {
        char caracter = evt.getKeyChar();
        if (!(Character.isDigit(caracter)) && (caracter != KeyEvent.VK_BACK_SPACE) && (caracter != KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }

    /**
     *
     * @return
     */
    public String nombre() {
        return JLnombre.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBcorridas3;
    private javax.swing.JButton JBcorridas4;
    private javax.swing.JButton JBdistancias1;
    private javax.swing.JButton JBfrecuencias1;
    private javax.swing.JButton JBgenerar;
    private javax.swing.JButton JBguardar;
    private javax.swing.JButton JBkolgomorov1;
    private javax.swing.JButton JBlimpiar;
    private javax.swing.JButton JBpoker1;
    private javax.swing.JButton JBpromedios1;
    private javax.swing.JButton JBseries1;
    private javax.swing.JLabel JLcorridas3;
    private javax.swing.JLabel JLcorridas4;
    private javax.swing.JLabel JLdistancias1;
    private javax.swing.JLabel JLfrecuencias1;
    private javax.swing.JLabel JLkolgomorov1;
    private javax.swing.JLabel JLnombre;
    private javax.swing.JLabel JLperiodo;
    private javax.swing.JLabel JLpoker1;
    private javax.swing.JLabel JLpromedio1;
    private javax.swing.JLabel JLseries1;
    private javax.swing.JPanel JPencabezado;
    private javax.swing.JPanel JPnumerosgenerados;
    private javax.swing.JPanel JPpruebas;
    private javax.swing.JPanel JPvariables;
    private javax.swing.JTextField JTmodulo;
    private javax.swing.JTextField JTn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
