/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.udec.simuladorpeaje.vista;

import com.itextpdf.text.DocumentException;
import com.udec.simuladorpeaje.logica.*;
import com.udec.simuladorpeaje.toFile.ToExcel;
import com.udec.simuladorpeaje.toFile.toPDF;

import javax.swing.*;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PedroD
 */
public class JPSimulacion extends javax.swing.JPanel {

    private ArrayList<Double> numeros1;
    private ArrayList<Double> numeros2;
    private ArrayList<Double> numeros3;
    private ArrayList<Double> numeros4;
    private JPSA jpanima;
    private ArrayList<Vehiculo> alv;
    private ArrayList<ArrayList<String>> tabla;
    private ArrayList<ArrayList<String>> tablafondo;
    private ArrayList<ArrayList<String>> tablafondoextra;
    private ArrayList<ArrayList<String>> tablafondoextra2;
    private Boolean extra;
    private ArrayList<Caseta> alc = new ArrayList<>();
    private String texto;
    private ArrayList<String> text;
    private ArrayList<String> colasSize;

    /**
     * Creates new form JPSimulacion
     */
    public JPSimulacion() {
        this.numeros1 = new ArrayList<>();
        this.numeros2 = new ArrayList<>();
        this.numeros3 = new ArrayList<>();
        this.numeros4 = new ArrayList<>();
        this.alv = new ArrayList<>();
        this.tabla = new ArrayList<>();
        this.alc = new ArrayList<>();
        this.tablafondo = new ArrayList<>();
        this.tablafondoextra = new ArrayList<>();
        this.tablafondoextra2 = new ArrayList<>();
        this.extra = new Boolean(false);
        this.colasSize = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPnumerosaleatorios = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLatencion = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLtiemposllegadas = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLvehiculos = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLtelepeajes = new javax.swing.JList();
        JBatencion = new javax.swing.JButton();
        JBtelepeaje = new javax.swing.JButton();
        JBvehiculos = new javax.swing.JButton();
        JBtiempsollegadas = new javax.swing.JButton();
        JPBllegada = new javax.swing.JProgressBar();
        JLprogresollegada = new javax.swing.JLabel();
        JLprogresovehiculos = new javax.swing.JLabel();
        JPBvehiculos = new javax.swing.JProgressBar();
        JLprogresotelepeaje = new javax.swing.JLabel();
        JPBtelepeaje = new javax.swing.JProgressBar();
        JPBatencion = new javax.swing.JProgressBar();
        JLprogresoatencion = new javax.swing.JLabel();
        JBvaciarlistas = new javax.swing.JButton();
        JPsimulacion = new javax.swing.JPanel();
        JBsimular = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JBanimacion = new javax.swing.JButton();
        JBtopdf = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(952, 597));
        setMinimumSize(new java.awt.Dimension(952, 597));

        JPnumerosaleatorios.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lista Numero Aleatorios"));

        jScrollPane4.setViewportView(jLatencion);

        jScrollPane1.setViewportView(jLtiemposllegadas);

        jScrollPane2.setViewportView(jLvehiculos);

        jScrollPane3.setViewportView(jLtelepeajes);

        JBatencion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1408783506_shine_21.png"))); // NOI18N
        JBatencion.setText("Cargar numeros-T. atención");
        JBatencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBatencionActionPerformed(evt);
            }
        });

        JBtelepeaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1408783506_shine_21.png"))); // NOI18N
        JBtelepeaje.setText("Cargar numeros-Telepeaje");
        JBtelepeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtelepeajeActionPerformed(evt);
            }
        });

        JBvehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1408783506_shine_21.png"))); // NOI18N
        JBvehiculos.setText("Cargar numeros-T. vehiculo");
        JBvehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBvehiculosActionPerformed(evt);
            }
        });

        JBtiempsollegadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1408783506_shine_21.png"))); // NOI18N
        JBtiempsollegadas.setText("Cargar numeros-T. llegada");
        JBtiempsollegadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtiempsollegadasActionPerformed(evt);
            }
        });

        JPBllegada.setStringPainted(true);

        JLprogresollegada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLprogresollegada.setText("  ");

        JLprogresovehiculos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLprogresovehiculos.setText("  ");

        JPBvehiculos.setStringPainted(true);

        JLprogresotelepeaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLprogresotelepeaje.setText("  ");

        JPBtelepeaje.setStringPainted(true);

        JPBatencion.setStringPainted(true);

        JLprogresoatencion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLprogresoatencion.setText("  ");

        JBvaciarlistas.setText("Vaciar Listas");
        JBvaciarlistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBvaciarlistasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPnumerosaleatoriosLayout = new javax.swing.GroupLayout(JPnumerosaleatorios);
        JPnumerosaleatorios.setLayout(JPnumerosaleatoriosLayout);
        JPnumerosaleatoriosLayout.setHorizontalGroup(
            JPnumerosaleatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnumerosaleatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPnumerosaleatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBtiempsollegadas, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JPBllegada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLprogresollegada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JPnumerosaleatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JPBvehiculos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JBvehiculos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(JLprogresovehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JPnumerosaleatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JLprogresotelepeaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JBtelepeaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(JPBtelepeaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JPnumerosaleatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JBatencion, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(JLprogresoatencion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPBatencion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPnumerosaleatoriosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBvaciarlistas)
                .addContainerGap())
        );
        JPnumerosaleatoriosLayout.setVerticalGroup(
            JPnumerosaleatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPnumerosaleatoriosLayout.createSequentialGroup()
                .addGroup(JPnumerosaleatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBvehiculos)
                    .addComponent(JBtiempsollegadas)
                    .addComponent(JBtelepeaje)
                    .addComponent(JBatencion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPnumerosaleatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JPnumerosaleatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPnumerosaleatoriosLayout.createSequentialGroup()
                        .addComponent(JLprogresollegada, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JPBllegada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPnumerosaleatoriosLayout.createSequentialGroup()
                        .addComponent(JLprogresovehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JPBvehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPnumerosaleatoriosLayout.createSequentialGroup()
                        .addComponent(JLprogresotelepeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JPBtelepeaje, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPnumerosaleatoriosLayout.createSequentialGroup()
                        .addComponent(JLprogresoatencion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JPBatencion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(JBvaciarlistas)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        JPsimulacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Simulación"));

        JBsimular.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JBsimular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start-icon.png"))); // NOI18N
        JBsimular.setText("Iniciar Simulación");
        JBsimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsimularActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        JBanimacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JBanimacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anima.png"))); // NOI18N
        JBanimacion.setText("Animación");
        JBanimacion.setEnabled(false);
        JBanimacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBanimacionActionPerformed(evt);
            }
        });

        JBtopdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf.png"))); // NOI18N
        JBtopdf.setText("Guardar reporte en PDF");
        JBtopdf.setEnabled(false);
        JBtopdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtopdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPsimulacionLayout = new javax.swing.GroupLayout(JPsimulacion);
        JPsimulacion.setLayout(JPsimulacionLayout);
        JPsimulacionLayout.setHorizontalGroup(
            JPsimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPsimulacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPsimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                    .addGroup(JPsimulacionLayout.createSequentialGroup()
                        .addComponent(JBsimular, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBtopdf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBanimacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        JPsimulacionLayout.setVerticalGroup(
            JPsimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPsimulacionLayout.createSequentialGroup()
                .addGroup(JPsimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPsimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBanimacion)
                        .addComponent(JBtopdf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JBsimular, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPnumerosaleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPsimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPnumerosaleatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPsimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBtiempsollegadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtiempsollegadasActionPerformed
        try {
            this.cargar(numeros1, jLtiemposllegadas, JPBllegada, JLprogresollegada);
        } catch (IOException ex) {
            Logger.getLogger(JPSimulacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(JPSimulacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBtiempsollegadasActionPerformed

    private void JBsimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsimularActionPerformed
        simulacion();
    }//GEN-LAST:event_JBsimularActionPerformed

    private void JBvehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBvehiculosActionPerformed
        try {
            this.cargar(numeros2, jLvehiculos, JPBvehiculos, JLprogresovehiculos);
        } catch (IOException ex) {
            Logger.getLogger(JPSimulacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(JPSimulacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBvehiculosActionPerformed

    private void JBtelepeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtelepeajeActionPerformed
        try {
            this.cargar(numeros3, jLtelepeajes, JPBtelepeaje, JLprogresotelepeaje);
        } catch (IOException ex) {
            Logger.getLogger(JPSimulacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(JPSimulacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBtelepeajeActionPerformed

    private void JBatencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBatencionActionPerformed
        try {
            this.cargar(numeros4, jLatencion, JPBatencion, JLprogresoatencion);
        } catch (IOException ex) {
            Logger.getLogger(JPSimulacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(JPSimulacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBatencionActionPerformed

    private void JBanimacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBanimacionActionPerformed
        jpanima = new JPSA(alc);
        jpanima.setAlv(alv);

        com.udec.simuladorpeaje.vista.Run.gen.cargarP(jpanima);
    }//GEN-LAST:event_JBanimacionActionPerformed

    private void JBtopdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtopdfActionPerformed
        try {
            reporte();
        } catch (DocumentException ex) {
            Logger.getLogger(JPSimulacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JPSimulacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JPSimulacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBtopdfActionPerformed

    private void JBvaciarlistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBvaciarlistasActionPerformed
        numeros1 = new ArrayList<>();
        numeros2 = new ArrayList<>();
        numeros3 = new ArrayList<>();
        numeros4 = new ArrayList<>();
        jLatencion.setModel(new DefaultListModel());
        jLtelepeajes.setModel(new DefaultListModel());
        jLvehiculos.setModel(new DefaultListModel());
        jLtiemposllegadas.setModel(new DefaultListModel());
        JLprogresoatencion.setText("");
        JLprogresollegada.setText("");
        JLprogresotelepeaje.setText("");
        JLprogresovehiculos.setText("");
        JPBatencion.setValue(0);
        JPBllegada.setValue(0);
        JPBtelepeaje.setValue(0);
        JPBvehiculos.setValue(0);
    }//GEN-LAST:event_JBvaciarlistasActionPerformed

    private void reporte() throws DocumentException, FileNotFoundException, IOException {
        toPDF sfile = new toPDF();
        sfile.guardar(this.texto, tabla, tablafondo, tablafondoextra, extra, text, colasSize, tablafondoextra2);
    }

    private void cargar(ArrayList<Double> numeros, JList jlist, JProgressBar jpb, JLabel label) throws IOException, InterruptedException {

        ToExcel file = new ToExcel();
        file.cargar(numeros, jpb, jlist, label);
    }

    private boolean compruebalongitud() {
        if (numeros1.size() == numeros2.size() && numeros2.size() == numeros3.size() && numeros3.size() == numeros4.size()) {
            return true;
        }
        return false;
    }

    private boolean compruebaVacio() {
        if (!(numeros1.isEmpty() || numeros2.isEmpty() || numeros3.isEmpty() || numeros4.isEmpty())) {
            return true;
        }
        return false;
    }

    private void simulacion() {

        if (!compruebalongitud()) {
            JOptionPane.showMessageDialog(this, "Por favor ingresar numeros aleatorios con el mismo periodo", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            if (!compruebaVacio()) {
                JOptionPane.showMessageDialog(this, "Por favor ingrese todas las lista denumeros aleatorios pedidas", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                com.udec.simuladorpeaje.vista.Run.gen.update();
                this.jTextArea1.setText("");
                this.tabla = new ArrayList<>();
                this.tablafondo = new ArrayList<>();
                this.tablafondoextra = new ArrayList<>();
                this.tablafondoextra2 = new ArrayList<>();
                Identificador id = new Identificador(numeros1, numeros2, numeros3, numeros4, Configuracion.getInstancia());
                ArrayList<Vehiculo> vehiculos = id.lista();
//********************************************************************************************************************************************************
//*****************************************************Simulación*****************************************************************************************
                ThreadSistema tll = new ThreadSistema();
                this.alc = new ArrayList<>();
                for (Caseta c : Configuracion.getInstancia().getAlc()) {
                    this.alc.add(new Caseta(c));
                }

                ArrayList<Vehiculo> alvs = new ArrayList<>();
                if (cantidadCasetasTipo(0, alc)) {
                    for (Vehiculo v : vehiculos) {
                        if (!v.isTelepeaje()) {
                            alvs.add(v);
                        }
                    }
                    for (Vehiculo vehiculo : alvs) {
                        vehiculos.remove(vehiculo);
                    }
                }
                if (cantidadCasetasTipo(1, alc)) {
                    for (Vehiculo vehiculo : vehiculos) {
                        if (vehiculo.isTelepeaje()) {
                            vehiculo.setTelepeaje(false);
                        }
                    }

                }
                System.out.println("Servers " + alc.toString());
                alv = new ArrayList<>();
                for (Vehiculo v : vehiculos) {
                    alv.add(new Vehiculo(v));
                }
                this.jTextArea1.setText("");

                System.out.println("size v" + vehiculos.size());
                tll.start(vehiculos, alc, Configuracion.getInstancia().getHoraInicio());
                this.text = tll.getTextoExtra();
                ArrayList<Vehiculo> alvDenied = tll.getAlvrechazados();
                if (!alvs.isEmpty()) {
                    this.texto = "\n\nVehiculos aceptados por sistema" + id.toStringCantidades(alv, true, tablafondo) + "\n\nVehiculos rechazados por sistema" + id.toStringCantidades(alvs, false, tablafondoextra);
                    if (!alvDenied.isEmpty()) {
                        this.jTextArea1.setText(tll.toString() + "\n\nVehiculos aceptados por sistema" + id.toStringCantidades(alv, true, tablafondo) + "\n\nVehiculos rechazados por sistema" + id.toStringCantidades(alvs, false, tablafondoextra) + "\n\nVehiculos rechazados por falta de atención" + id.toStringCantidades(alvDenied, false, tablafondoextra2));
                    } else {
                        this.jTextArea1.setText(tll.toString() + "\n\nVehiculos aceptados por sistema" + id.toStringCantidades(alv, true, tablafondo) + "\n\nVehiculos rechazados por sistema" + id.toStringCantidades(alvs, false, tablafondoextra));
                        System.out.println("tablafondoextra\n" + tablafondoextra);
                    }
                } else {
                   
                    System.out.println("tablafondoextra\n" + tablafondoextra);
                    if (!alvDenied.isEmpty()) {
                        this.jTextArea1.setText(tll.toString() + id.toStringCantidades(alv, true, tablafondo) + "\n\nVehiculos rechazados por sistema" + "\n\nVehiculos rechazados por falta de atención" + id.toStringCantidades(alvDenied, false, tablafondoextra2));
                    } else {
                        this.jTextArea1.setText(tll.toString() + id.toStringCantidades(alv, true, tablafondo));
                    }
                }
                this.JBanimacion.setEnabled(true);
                this.JBtopdf.setEnabled(true);
                tabla = tll.getTabla();
                this.colasSize = tll.getColasSize();
                System.out.println("Rechazados  " + tll.getAlvrechazados().size());
            }

        }
    }

    private Boolean cantidadCasetasTipo(int tipo, ArrayList<Caseta> casetas) {
        int cantidad = 0;
        for (Caseta caseta : casetas) {
            if (caseta.getTipo() == tipo) {
                cantidad++;
            }
        }
        System.out.println("Cantidada de servidores de tipo " + tipo + ": " + cantidad + " Tamaño casetas " + casetas.size());
        return cantidad == casetas.size();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBanimacion;
    private javax.swing.JButton JBatencion;
    private javax.swing.JButton JBsimular;
    private javax.swing.JButton JBtelepeaje;
    private javax.swing.JButton JBtiempsollegadas;
    private javax.swing.JButton JBtopdf;
    private javax.swing.JButton JBvaciarlistas;
    private javax.swing.JButton JBvehiculos;
    private javax.swing.JLabel JLprogresoatencion;
    private javax.swing.JLabel JLprogresollegada;
    private javax.swing.JLabel JLprogresotelepeaje;
    private javax.swing.JLabel JLprogresovehiculos;
    private javax.swing.JProgressBar JPBatencion;
    private javax.swing.JProgressBar JPBllegada;
    private javax.swing.JProgressBar JPBtelepeaje;
    private javax.swing.JProgressBar JPBvehiculos;
    private javax.swing.JPanel JPnumerosaleatorios;
    private javax.swing.JPanel JPsimulacion;
    private javax.swing.JList jLatencion;
    private javax.swing.JList jLtelepeajes;
    private javax.swing.JList jLtiemposllegadas;
    private javax.swing.JList jLvehiculos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
