/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.udec.simuladorpeaje.vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

import com.udec.simuladorpeaje.logica.Configuracion;

/**
 *
 * @author Estudiante
 */
public class JFmainTabble extends javax.swing.JFrame {

    private final JPSimulacion JPS;
    private final JPMezclaI jmI;
    private final JPMezclaII jmII;
    private final JPMitchelMoore jmm;
    private final JPCMixto jcm;
    private final JPCMultiplicativo jm;
    private final JPGreen jg;
    private final JPFibonacci jf;
    private final JPCuadratico jc;
    private final JPMixto jmx;
    private JPConfiguracion jpc;
    private JPconfiguracionatencion jcha;
    private JPconfiguracionescasetas jcc;
    private JPconfiguracionhoras jch;
    private Boolean flag;
    private Boolean flag1;
    private Boolean flag2;
    private Boolean flag3;
    private Boolean flag4;

    /**
     * Creates new form JFmainTabble
     */
    public JFmainTabble() {
        this.jmx = new JPMixto();
        this.jc = new JPCuadratico();
        this.jf = new JPFibonacci();
        this.jg = new JPGreen();
        this.jm = new JPCMultiplicativo();
        this.jcm = new JPCMixto();
        this.jmm = new JPMitchelMoore();
        this.jmII = new JPMezclaII();
        this.jmI = new JPMezclaI();
        this.JPS = new JPSimulacion();
        this.jpc = new JPConfiguracion();
        this.jcha = new JPconfiguracionatencion();
        this.jcc = new JPconfiguracionescasetas();
        this.jch = new JPconfiguracionhoras();
        this.flag = new Boolean(true);
        this.flag1 = new Boolean(true);
        this.flag2 = new Boolean(true);
        this.flag3 = new Boolean(true);
        this.flag4 = new Boolean(true);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        JTareatrabajo = new javax.swing.JTabbedPane();
        JMBopciones = new javax.swing.JMenuBar();
        JMgeneradores = new javax.swing.JMenu();
        JScongruenciales = new javax.swing.JPopupMenu.Separator();
        JMIcmixto = new javax.swing.JMenuItem();
        JMIcmultiplicativo = new javax.swing.JMenuItem();
        JMIccuadratico = new javax.swing.JMenuItem();
        JSmezclas = new javax.swing.JPopupMenu.Separator();
        JMImezclas1 = new javax.swing.JMenuItem();
        JMImezclas2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        JMIfibonacci = new javax.swing.JMenuItem();
        JMIgreen = new javax.swing.JMenuItem();
        JMImitchelmoore = new javax.swing.JMenuItem();
        JMImixto = new javax.swing.JMenuItem();
        JMsimulacion = new javax.swing.JMenu();
        JMIpeaje = new javax.swing.JMenuItem();
        JSsepardor = new javax.swing.JPopupMenu.Separator();
        JMconfiguraciones = new javax.swing.JMenu();
        JMIprobabilidadesmedias = new javax.swing.JMenuItem();
        JMIcasetas = new javax.swing.JMenuItem();
        JMIcomportamientohoras = new javax.swing.JMenuItem();
        JMIatencion = new javax.swing.JMenuItem();
        JSseparador = new javax.swing.JPopupMenu.Separator();
        JMIporDefecto = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Simulación");
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(1024, 720));
        setMinimumSize(new java.awt.Dimension(800, 720));
        setPreferredSize(new java.awt.Dimension(980, 700));
        setResizable(false);

        JTareatrabajo.setBackground(new java.awt.Color(204, 204, 204));
        JTareatrabajo.setForeground(new java.awt.Color(204, 204, 204));

        JMgeneradores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator40.png"))); // NOI18N
        JMgeneradores.setText("Generadores");

        JScongruenciales.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Congruenciales", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        JScongruenciales.setForeground(new java.awt.Color(255, 255, 255));
        JScongruenciales.setPreferredSize(new java.awt.Dimension(0, 15));
        JMgeneradores.add(JScongruenciales);

        JMIcmixto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        JMIcmixto.setText("Mixto");
        JMIcmixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIcmixtoActionPerformed(evt);
            }
        });
        JMgeneradores.add(JMIcmixto);

        JMIcmultiplicativo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        JMIcmultiplicativo.setText("Multiplicativo");
        JMIcmultiplicativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIcmultiplicativoActionPerformed(evt);
            }
        });
        JMgeneradores.add(JMIcmultiplicativo);

        JMIccuadratico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        JMIccuadratico.setText("Cuadratico");
        JMIccuadratico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIccuadraticoActionPerformed(evt);
            }
        });
        JMgeneradores.add(JMIccuadratico);

        JSmezclas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Mezclas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        JSmezclas.setForeground(new java.awt.Color(255, 255, 255));
        JSmezclas.setPreferredSize(new java.awt.Dimension(0, 15));
        JMgeneradores.add(JSmezclas);

        JMImezclas1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        JMImezclas1.setText("Mezclas I");
        JMImezclas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMImezclas1ActionPerformed(evt);
            }
        });
        JMgeneradores.add(JMImezclas1);

        JMImezclas2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        JMImezclas2.setText("Mezclas II");
        JMImezclas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMImezclas2ActionPerformed(evt);
            }
        });
        JMgeneradores.add(JMImezclas2);

        jSeparator3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(), "Aditivos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setPreferredSize(new java.awt.Dimension(0, 15));
        JMgeneradores.add(jSeparator3);

        JMIfibonacci.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        JMIfibonacci.setText("Fibonacci");
        JMIfibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIfibonacciActionPerformed(evt);
            }
        });
        JMgeneradores.add(JMIfibonacci);

        JMIgreen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        JMIgreen.setText("Green");
        JMIgreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIgreenActionPerformed(evt);
            }
        });
        JMgeneradores.add(JMIgreen);

        JMImitchelmoore.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        JMImitchelmoore.setText("Mitchel Moore");
        JMImitchelmoore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMImitchelmooreActionPerformed(evt);
            }
        });
        JMgeneradores.add(JMImitchelmoore);

        JMImixto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        JMImixto.setText("Mixto");
        JMImixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMImixtoActionPerformed(evt);
            }
        });
        JMgeneradores.add(JMImixto);

        JMBopciones.add(JMgeneradores);

        JMsimulacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/analytics2.png"))); // NOI18N
        JMsimulacion.setText("Simulación");

        JMIpeaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ford-GT-icon.png"))); // NOI18N
        JMIpeaje.setText("Peaje");
        JMIpeaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIpeajeActionPerformed(evt);
            }
        });
        JMsimulacion.add(JMIpeaje);
        JMsimulacion.add(JSsepardor);

        JMconfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tools3.png"))); // NOI18N
        JMconfiguraciones.setText("Configuraciones");

        JMIprobabilidadesmedias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tasks2.png"))); // NOI18N
        JMIprobabilidadesmedias.setText("Probabilidades y Medias");
        JMIprobabilidadesmedias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIprobabilidadesmediasActionPerformed(evt);
            }
        });
        JMconfiguraciones.add(JMIprobabilidadesmedias);

        JMIcasetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home107.png"))); // NOI18N
        JMIcasetas.setText("Casetas");
        JMIcasetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIcasetasActionPerformed(evt);
            }
        });
        JMconfiguraciones.add(JMIcasetas);

        JMIcomportamientohoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clock96.png"))); // NOI18N
        JMIcomportamientohoras.setText("Comportamiento de las Horas");
        JMIcomportamientohoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIcomportamientohorasActionPerformed(evt);
            }
        });
        JMconfiguraciones.add(JMIcomportamientohoras);

        JMIatencion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/event5.png"))); // NOI18N
        JMIatencion.setText("Atención de Servidores");
        JMIatencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIatencionActionPerformed(evt);
            }
        });
        JMconfiguraciones.add(JMIatencion);
        JMconfiguraciones.add(JSseparador);

        JMIporDefecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delivery21.png"))); // NOI18N
        JMIporDefecto.setText("Por defecto");
        JMIporDefecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIporDefectoActionPerformed(evt);
            }
        });
        JMconfiguraciones.add(JMIporDefecto);

        JMsimulacion.add(JMconfiguraciones);

        JMBopciones.add(JMsimulacion);

        setJMenuBar(JMBopciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTareatrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTareatrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JMIcmixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIcmixtoActionPerformed
        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), false);
        JTareatrabajo.addTab(jcm.nombre(), jcm);
        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
        JTareatrabajo.setSelectedIndex(JTareatrabajo.getTabCount() - 1);
    }//GEN-LAST:event_JMIcmixtoActionPerformed

    private void JMIcmultiplicativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIcmultiplicativoActionPerformed
        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), false);
        JTareatrabajo.addTab(jm.nombre(), jm);
        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
        JTareatrabajo.setSelectedIndex(JTareatrabajo.getTabCount() - 1);
    }//GEN-LAST:event_JMIcmultiplicativoActionPerformed

    private void JMIccuadraticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIccuadraticoActionPerformed
        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), false);
        JTareatrabajo.addTab(jc.nombre(), jc);
        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
        JTareatrabajo.setSelectedIndex(JTareatrabajo.getTabCount() - 1);
    }//GEN-LAST:event_JMIccuadraticoActionPerformed

    private void JMIfibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIfibonacciActionPerformed
        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), false);
        JTareatrabajo.addTab(jf.nombre(), jf);
        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
        JTareatrabajo.setSelectedIndex(JTareatrabajo.getTabCount() - 1);
    }//GEN-LAST:event_JMIfibonacciActionPerformed

    private void JMIgreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIgreenActionPerformed
        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), false);
        JTareatrabajo.addTab(jg.nombre(), jg);
        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
        JTareatrabajo.setSelectedIndex(JTareatrabajo.getTabCount() - 1);
    }//GEN-LAST:event_JMIgreenActionPerformed

    private void JMImitchelmooreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMImitchelmooreActionPerformed
        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), false);
        JTareatrabajo.addTab(jmm.nombre(), jmm);
        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
        JTareatrabajo.setSelectedIndex(JTareatrabajo.getTabCount() - 1);
    }//GEN-LAST:event_JMImitchelmooreActionPerformed

    private void JMImezclas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMImezclas2ActionPerformed
        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), false);
        JTareatrabajo.addTab(jmII.nombre(), jmII);
        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
        JTareatrabajo.setSelectedIndex(JTareatrabajo.getTabCount() - 1);
    }//GEN-LAST:event_JMImezclas2ActionPerformed

    private void JMIpeajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIpeajeActionPerformed
        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), false);
        JTareatrabajo.addTab("Simulación", JPS);
        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
        JTareatrabajo.setSelectedIndex(JTareatrabajo.getTabCount() - 1);
    }//GEN-LAST:event_JMIpeajeActionPerformed

    private void JMImezclas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMImezclas1ActionPerformed
        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), false);
        JTareatrabajo.addTab(jmI.nombre(), jmI);
        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
        JTareatrabajo.setSelectedIndex(JTareatrabajo.getTabCount() - 1);
    }//GEN-LAST:event_JMImezclas1ActionPerformed

    private void JMImixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMImixtoActionPerformed
        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), false);
        JTareatrabajo.addTab(jmx.nombre(), jmx);
        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
        JTareatrabajo.setSelectedIndex(JTareatrabajo.getTabCount() - 1);
    }//GEN-LAST:event_JMImixtoActionPerformed

    private void JMIprobabilidadesmediasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIprobabilidadesmediasActionPerformed

        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), flag1);
        JTareatrabajo.addTab("Probabilidades y Medias", jpc);
        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
        JTareatrabajo.setSelectedIndex(JTareatrabajo.getTabCount() - 1);

    }//GEN-LAST:event_JMIprobabilidadesmediasActionPerformed

    private void JMIatencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIatencionActionPerformed
        flag = Boolean.TRUE;

        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), flag4);
        JTareatrabajo.addTab("Atención de Servidores", jcha);
        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
        JTareatrabajo.setSelectedIndex(JTareatrabajo.getTabCount() - 1);

    }//GEN-LAST:event_JMIatencionActionPerformed

    private void JMIcomportamientohorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIcomportamientohorasActionPerformed

        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), flag3);
        JTareatrabajo.addTab("Comportamiento de las horas", jch);
        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
        JTareatrabajo.setSelectedIndex(JTareatrabajo.getTabCount() - 1);

    }//GEN-LAST:event_JMIcomportamientohorasActionPerformed

    private void JMIcasetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIcasetasActionPerformed
        flag2 = true;

        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), flag2);
        JTareatrabajo.addTab("Casetas", jcc);
        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
        JTareatrabajo.setSelectedIndex(JTareatrabajo.getTabCount() - 1);

    }//GEN-LAST:event_JMIcasetasActionPerformed

    private void JMIporDefectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIporDefectoActionPerformed
        JTareatrabajo.remove(this.jcc);
        JTareatrabajo.remove(this.jch);
        JTareatrabajo.remove(this.jpc);
        JTareatrabajo.remove(this.jcha);
        Configuracion.porDefecto();
        this.jcc = new JPconfiguracionescasetas();
        this.jch = new JPconfiguracionhoras();
        this.jcha = new JPconfiguracionatencion();
        this.jpc = new JPConfiguracion();

        JOptionPane.showMessageDialog(null, "Carga por defecto exitosa", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_JMIporDefectoActionPerformed

    private void atencion() {
//        flag = Boolean.TRUE;
//        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), flag4);
//        JTareatrabajo.addTab("Ateción de Servidores", jcha);
//        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
//        flag4 = true;
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("images/cars.png"));

        return retValue;
    }

    /**
     *
     * @param a
     */
    public void cargarP(JPSA a) {
        JTareatrabajo.remove(a);
        PanelTab btc = new PanelTab(JTareatrabajo, JTareatrabajo.getComponentCount(), false);
        JTareatrabajo.addTab("Animación", a);
        JTareatrabajo.setTabComponentAt(JTareatrabajo.getTabCount() - 1, btc);
        JTareatrabajo.setSelectedIndex(JTareatrabajo.getTabCount() - 1);
    }

    /**
     *
     */
    public void update() {
        this.jcc.nuevaConfigSneak();
    }

    /**
     *
     */
    public void actualizaDesdeCasetas() {
        this.jcha.cargar(Configuracion.getInstancia().getAlc());
        JTareatrabajo.remove(jcha);
        jcha = new JPconfiguracionatencion();
        if (flag) {
            this.atencion();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar JMBopciones;
    private javax.swing.JMenuItem JMIatencion;
    private javax.swing.JMenuItem JMIcasetas;
    private javax.swing.JMenuItem JMIccuadratico;
    private javax.swing.JMenuItem JMIcmixto;
    private javax.swing.JMenuItem JMIcmultiplicativo;
    private javax.swing.JMenuItem JMIcomportamientohoras;
    private javax.swing.JMenuItem JMIfibonacci;
    private javax.swing.JMenuItem JMIgreen;
    private javax.swing.JMenuItem JMImezclas1;
    private javax.swing.JMenuItem JMImezclas2;
    private javax.swing.JMenuItem JMImitchelmoore;
    private javax.swing.JMenuItem JMImixto;
    private javax.swing.JMenuItem JMIpeaje;
    private javax.swing.JMenuItem JMIporDefecto;
    private javax.swing.JMenuItem JMIprobabilidadesmedias;
    private javax.swing.JMenu JMconfiguraciones;
    private javax.swing.JMenu JMgeneradores;
    private javax.swing.JMenu JMsimulacion;
    private javax.swing.JPopupMenu.Separator JScongruenciales;
    private javax.swing.JPopupMenu.Separator JSmezclas;
    private javax.swing.JPopupMenu.Separator JSseparador;
    private javax.swing.JPopupMenu.Separator JSsepardor;
    private javax.swing.JTabbedPane JTareatrabajo;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
